# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class DownloadInboxCleaner < Formula
  desc "Cautious macOS Downloads-folder cleaner"
  homepage "https://github.com/stawan15/Download-scanner"
  version "1.1.5"
  depends_on :macos

  if Hardware::CPU.intel?
    url "https://github.com/stawan15/Download-scanner/releases/download/v1.1.5/Download-scanner_1.1.5_darwin_amd64.tar.gz"
    sha256 "e7d16588b3358ba38b9a16354302f32da31bc5ab88ec801a9d39eda1724f48ce"

    define_method(:install) do
      bin.install "cleaner"
    end
  end
  if Hardware::CPU.arm?
    url "https://github.com/stawan15/Download-scanner/releases/download/v1.1.5/Download-scanner_1.1.5_darwin_arm64.tar.gz"
    sha256 "f7f64a044d35df0586ffe780aa994fab1cf1620f30182eb6dbf6816115978ffe"

    define_method(:install) do
      bin.install "cleaner"
    end
  end
end
