# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class DownloadInboxCleaner < Formula
  desc "Cautious macOS Downloads-folder cleaner"
  homepage "https://github.com/stawan15/Download-scanner"
  version "1.1.4"
  depends_on :macos

  if Hardware::CPU.intel?
    url "https://github.com/stawan15/Download-scanner/releases/download/v1.1.4/Download-scanner_1.1.4_darwin_amd64.tar.gz"
    sha256 "8f1ec505cecfb6f1276472e1dcb82f90eff4cf8d7b329b8f5e17376330119b4c"

    define_method(:install) do
      bin.install "cleaner"
    end
  end
  if Hardware::CPU.arm?
    url "https://github.com/stawan15/Download-scanner/releases/download/v1.1.4/Download-scanner_1.1.4_darwin_arm64.tar.gz"
    sha256 "6eec9a670c885c89fb6c5eed8af5d98603b2ff48f09407c8c7c64231c8966982"

    define_method(:install) do
      bin.install "cleaner"
    end
  end
end
