# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class DownloadInboxCleaner < Formula
  desc "Cautious macOS Downloads-folder cleaner"
  homepage "https://github.com/stawan15/Download-scanner"
  version "1.1.1"
  depends_on :macos

  if Hardware::CPU.intel?
    url "https://github.com/stawan15/Download-scanner/releases/download/v1.1.1/Download-scanner_1.1.1_darwin_amd64.tar.gz"
    sha256 "7edd3507460dc56225c4874c513e81df1d3dec6cb3334a19df5329d230d09494"

    define_method(:install) do
      bin.install "cleaner"
    end
  end

  if Hardware::CPU.arm?
    url "https://github.com/stawan15/Download-scanner/releases/download/v1.1.1/Download-scanner_1.1.1_darwin_arm64.tar.gz"
    sha256 "b09342bf21d755e83ab301bf6882cb0fd0cd11d4c8457cd910f05c02af590d09"

    define_method(:install) do
      bin.install "cleaner"
    end
  end
end
