# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class KamalTui < Formula
  desc "A Terminal UI for Kamal deployments"
  homepage "https://github.com/stawan15/kamal-tui"
  version "2.3.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/stawan15/Kamal-TUI/releases/download/v2.3.0/kamal-tui_Darwin_x86_64.tar.gz"
      sha256 "4021234080aae6791bdf4d427f12677e2b36ed0e167ae5f8a4a0f05e1bb8fa5d"

      define_method(:install) do
        bin.install "kamal-tui"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/stawan15/Kamal-TUI/releases/download/v2.3.0/kamal-tui_Darwin_arm64.tar.gz"
      sha256 "a4782e9314c0d5b5ac4d315d239cf996729ed3ac4ed0a7cb5e2bcfdfb1622111"

      define_method(:install) do
        bin.install "kamal-tui"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/stawan15/Kamal-TUI/releases/download/v2.3.0/kamal-tui_Linux_x86_64.tar.gz"
      sha256 "3f8c4a645fac5a2c286ebc6fcac1fbec73fad6a901e64510f7ca07273925ce40"
      define_method(:install) do
        bin.install "kamal-tui"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/stawan15/Kamal-TUI/releases/download/v2.3.0/kamal-tui_Linux_arm64.tar.gz"
      sha256 "c722543197aa848cae5b1ae3a7ac3d4ec9fe6c7f9a49244be93bc7da89c591db"
      define_method(:install) do
        bin.install "kamal-tui"
      end
    end
  end
end
